version: 2
groups:
  - name: kubemasters
    targets:
      - _plugin: terraform
        resource_type: vsphere_virtual_machine.kubernetes-master
        dir: /stackstorm/orchestration-demos/terraform/kubernetes
        backend: remote
        target_mapping:
          uri: default_ip_address
    config:
      transport: ssh
      ssh:
        user: root
        connect-timeout: 300
        host-key-check: false
  - name: kubeworkers
    targets:
      - _plugin: terraform
        resource_type: vsphere_virtual_machine.kubernetes-worker
        dir: /stackstorm/orchestration-demos/terraform/kubernetes
        backend: remote
        target_mapping:
          uri: default_ip_address
    config:
      transport: ssh
      ssh:
        user: root
        connect-timeout: 300
        host-key-check: false
